### ISSUE TITLE
Problem in determining whether it is a TensorFlow API

### ISSUE THREAD

**Issue by tatianacv** [ponder-lab/ML#23]
When processing the following: 

https://github.com/ponder-lab/ML/blob/e4c4bee05c76189b2bc3c66a937eba2d27e1fe9a/com.ibm.wala.cast.python.test/data/tf2n.py#L1-L14

We found an error in determining whether we are dealing with a TensorFlow API. We found that the tensor analysis is empty:

https://github.com/ponder-lab/ML/blob/3e79634acf3d4a7b181acad66c3ce31a60d2c33b/com.ibm.wala.cast.python.ml.test/source/com/ibm/wala/cast/python/ml/test/TestTensorflowModel.java#L82

**Comment by khatchad** [comment]
In the upstream repo please. Also, could you open a PR with the failing test case?

**Comment by tatianacv** [comment]
> In the upstream repo please. Also, could you open a PR with the failing test case?

We discussed and decided to open the issue here because this issue arises with unmerged code.

**Comment by khatchad** [comment]
Do you have a PR with the failing case?

**Comment by tatianacv** [comment]
> Do you have a PR with the failing case?

Yes, I linked the issue to the PR now.

**Comment by khatchad** [comment]
Superceded by https://github.com/wala/ML/issues/49.
