### ISSUE TITLE
IllegalState when importing a second-level API directly

### ISSUE THREAD

**Issue by tatianacv** [ponder-lab/ML#28]
For the following example: 
```python
from tensorflow import random

def add(a, b):
  return a + b


c = add(random.gamma([10], [0.5, 1.5]), random.gamma([10], [1, 2.5]))
```

We get the following error: 
```
[ERROR]   TestTensorflowModel.testTf2:98->testTf2:113 » IllegalState Encountered unexpected API call.
```

This is from the second-level TF2 APIs, which have not yet been merged. Once we discuss what to do with the second-level APIs, I can create a PR for this failing test.

**Comment by tatianacv** [comment]
This happens because in line 85, we get `gamma` and for some reason this is not saved in the `symbolTable` the same way as in when you use `tf.etc`, e.g. `tf.random.gamma`. Therefore, when we iterate and decrease the `memberRef`, we don't get to `random` (lines 95-101)
https://github.com/ponder-lab/ML/blob/d763f49bbce8de2329b1799cd192c011ca502b1e/com.ibm.wala.cast.python.ml/source/com/ibm/wala/cast/python/ml/client/PythonTensorAnalysisEngine.java#L84-L101

**Comment by khatchad** [comment]
In the PR you are working on, please comment out this test case and add a `TODO` mentioning this issue.

**Comment by khatchad** [comment]
But I think this is solved by https://github.com/ponder-lab/ML/pull/24/commits/dcf3efba52c448090d5940c2cdb9785df39e1a93. Can you check?

**Comment by tatianacv** [comment]
No, it is not resolved by https://github.com/ponder-lab/ML/commit/dcf3efba52c448090d5940c2cdb9785df39e1a93. This issue has to do with how we process the API levels (https://github.com/ponder-lab/ML/issues/28#issuecomment-1599449946)

**Comment by tatianacv** [comment]
> In the PR you are working on, please comment out this test case and add a `TODO` mentioning this issue.

I have done this already!

**Comment by khatchad** [comment]
I need to see a stack trace. Do we have a PR that adds the failing test case?

**Comment by tatianacv** [comment]
> I need to see a stack trace. Do we have a PR that adds the failing test case?

No, because we haven't merged the second-level API PR to master.

**Comment by khatchad** [comment]
I don't think this is a bug in the master branch.

**Comment by khatchad** [comment]
What is the value of the API when the exception is thrown?

**Comment by khatchad** [comment]
Please submit a PR with a failing test case that fails with the current code in master then reopen.

**Comment by khatchad** [comment]
Does this issue occur in the upstream repo? If so, please file the issue there. Let's only use the issues here for problems in this repo. I'll close, but please reopen if it only occurs here.

**Comment by tatianacv** [comment]
Superseded by https://github.com/wala/ML/issues/60
